merge r8958 from the main trunk:
fix the following error on Solaris, by defining _POSIX_PTHREAD_SEMANTICS:
	gfprep.c:2955: too many arguments to function `sigwait'

this problem was introduced in r8392 (for #709)
to support SIGTERM/SIGINT/SIGHUP to remove replicas certainly